### ISSUE TITLE
getLeaderboardScore 오류 문의

### ISSUE THREAD

**Issue by yoopark** [42Statistics/42Stat-Backend#161]
### Query
```
  query GetLeaderboardScore(
    $pageSize: Int! = 50,
    $pageNumber: Int! = 1,
    $dateTemplate: DateTemplate! = CURR_MONTH
  ) {
    getLeaderboardScore {
      byDateTemplate(
        pageSize: $pageSize
        pageNumber: $pageNumber
        dateTemplate: $dateTemplate
      ) {
        data {
          me {
            userPreview {
              id
              login
              imgUrl
            }
            value
            rank
          }
          totalRanking {
            nodes {
              userPreview {
                id
                login
                imgUrl
              }
              value
              rank
            }
            totalCount
            pageSize
            pageNumber
          }
        }
        start
        end
      }
    }
  }
```

### 에러
```
{
  "errors": [
    {
      "message": "unknown top level operator: $match. If you have a field name that starts with a '$' symbol, consider using $getField or $setField.",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "getLeaderboardScore",
        "byDateTemplate"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "ok": 0,
          "code": 2,
          "codeName": "BadValue",
          "stacktrace": [
            "MongoServerError: unknown top level operator: $match. If you have a field name that starts with a '$' symbol, consider using $getField or $setField.",
            "    at Connection.onMessage (/app/node_modules/.pnpm/mongodb@5.1.0/node_modules/mongodb/src/cmap/connection.ts:393:20)",
            "    at MessageStream.<anonymous> (/app/node_modules/.pnpm/mongodb@5.1.0/node_modules/mongodb/src/cmap/connection.ts:224:56)",
            "    at MessageStream.emit (node:events:513:28)",
            "    at processIncomingData (/app/node_modules/.pnpm/mongodb@5.1.0/node_modules/mongodb/src/cmap/message_stream.ts:189:12)",
            "    at MessageStream._write (/app/node_modules/.pnpm/mongodb@5.1.0/node_modules/mongodb/src/cmap/message_stream.ts:70:5)",
            "    at writeOrBuffer (node:internal/streams/writable:392:12)",
            "    at _write (node:internal/streams/writable:333:10)",
            "    at MessageStream.Writable.write (node:internal/streams/writable:337:10)",
            "    at Socket.ondata (node:internal/streams/readable:766:22)",
            "    at Socket.emit (node:events:513:28)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

다른 필드는 되는데 얘만 안되네요

**Comment by jpham005** [comment]
다음 버전 합칠때 고쳐질 것 같습니다.
내부 로직에선 이미 수정해둔걸로 기억해요.
